/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newspoll;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import javax.swing.JLabel;

/**
 *
 * @author shayak
 */
public class HomePage extends javax.swing.JPanel {

    public User user;
    public News news;
    public int iterator = -1;

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        user = new User();

        initComponents();
        showNewLinkElements(false);
        showProfileElements(false);

        news = new News();

        nextNews();

    }

    public void nextNews() {
        lblHeadline.setText("<html><p>" + news.title.get(++iterator)
                + "</p></html>");
        switch (iterator) {
            case 0:
                lblIcon.setIcon(new javax.swing.ImageIcon(getClass()
                        .getResource("/resources/pic1.png")));
                break;

            case 1:
                lblIcon.setIcon(new javax.swing.ImageIcon(getClass()
                        .getResource("/resources/pic2.png")));
                break;

            case 2:
                lblIcon.setIcon(new javax.swing.ImageIcon(getClass()
                        .getResource("/resources/pic3.png")));
                break;

            case 3:
                lblIcon.setIcon(new javax.swing.ImageIcon(getClass()
                        .getResource("/resources/pic4.png")));
                break;

            default:;

        }
    }

    public void createUser(String username, String password, String fullName,
            String credits) {

        user.setUsername(username);
        user.setCredits(Integer.parseInt(credits));
        user.setFullName(fullName);

        //setting the user details in the profile section
        lblUsername.setText(lblUsername.getText() + " " + user.getUsername());
        lblFullName.setText(lblFullName.getText() + " " + user.getFullName());
        lblCredits.setText(lblCredits.getText() + " " + user.getCredits());
    }

    public static boolean openWebpage(URI uri) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(uri);
                return true;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return false;
    }

    public static boolean openWebpage(URL url) {
        try {
            return openWebpage(url.toURI());
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        btnBrowser = new javax.swing.JButton();
        btnNotFake = new javax.swing.JButton();
        btnFake = new javax.swing.JButton();
        lblHeadline = new javax.swing.JLabel();
        lblBlankWhite = new javax.swing.JLabel();
        lblBlankWhite.setVisible(false);
        btnProfile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLink = new javax.swing.JTextArea();
        btnPasteFromClipboard = new javax.swing.JButton();
        btnSubmitLink = new javax.swing.JButton();
        btnNewLink = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnSubmitAnotherLink = new javax.swing.JButton();
        btnGoBackToHome = new javax.swing.JButton();
        lblThanks = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        btnPollsByYou = new javax.swing.JButton();
        btnPollEngagement = new javax.swing.JButton();
        lblInfo1 = new javax.swing.JLabel();
        lblInfo2 = new javax.swing.JLabel();
        lblBackgroundImage = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(281, 500));
        setMinimumSize(new java.awt.Dimension(281, 500));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(281, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setText("image");
        add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, 210));

        btnBrowser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/browserButton.png"))); // NOI18N
        btnBrowser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrowser.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/browserButtonMousePressed.png"))); // NOI18N
        btnBrowser.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/browserButtonMousePressed.png"))); // NOI18N
        btnBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowserActionPerformed(evt);
            }
        });
        add(btnBrowser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 50, 80));

        btnNotFake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnNotFake.png"))); // NOI18N
        btnNotFake.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNotFake.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnNotFakeMouseOver.png"))); // NOI18N
        btnNotFake.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnNotFakeMouseOver.png"))); // NOI18N
        btnNotFake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotFakeActionPerformed(evt);
            }
        });
        add(btnNotFake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 130, 40));

        btnFake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnFake.png"))); // NOI18N
        btnFake.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFake.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnFakeMouseOver.png"))); // NOI18N
        btnFake.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnFakeMouseOver.png"))); // NOI18N
        btnFake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFakeActionPerformed(evt);
            }
        });
        add(btnFake, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 130, 40));

        lblHeadline.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        lblHeadline.setText("news headline");
        lblHeadline.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblHeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 80));

        lblBlankWhite.setBackground(new java.awt.Color(254, 254, 254));
        lblBlankWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/blank white.png"))); // NOI18N
        lblBlankWhite.setText("jLabel1");
        add(lblBlankWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 300, 350));

        btnProfile.setBorder(null);
        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 100, 50));
        btnProfile.setContentAreaFilled(false);

        txtLink.setColumns(20);
        txtLink.setForeground(new java.awt.Color(1, 1, 1));
        txtLink.setLineWrap(true);
        txtLink.setRows(5);
        txtLink.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLinkFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(txtLink);
        txtLink.setVisible(false);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, 100));

        btnPasteFromClipboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnPasteClip.png"))); // NOI18N
        btnPasteFromClipboard.setBorder(null);
        btnPasteFromClipboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPasteFromClipboard.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnPasteClipMouseOver.png"))); // NOI18N
        btnPasteFromClipboard.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnPasteClipMouseOver.png"))); // NOI18N
        btnPasteFromClipboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasteFromClipboardActionPerformed(evt);
            }
        });
        btnPasteFromClipboard.setVisible(false);
        add(btnPasteFromClipboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        btnSubmitLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/submitLinkButton.png"))); // NOI18N
        btnSubmitLink.setBorder(null);
        btnSubmitLink.setContentAreaFilled(false);
        btnSubmitLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmitLink.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/submitLinkButtonMouseOver.png"))); // NOI18N
        btnSubmitLink.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/submitLinkButtonMouseOver.png"))); // NOI18N
        btnSubmitLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitLinkActionPerformed(evt);
            }
        });
        btnSubmitLink.setVisible(false);
        add(btnSubmitLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        btnNewLink.setBorder(null);
        btnNewLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewLinkActionPerformed(evt);
            }
        });
        add(btnNewLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 100, 50));
        btnNewLink.setContentAreaFilled(false);

        btnHome.setBorder(null);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 100, 50));
        btnHome.setContentAreaFilled(false);

        btnSubmitAnotherLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/submitAnotherButton.png"))); // NOI18N
        btnSubmitAnotherLink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 166, 166)));
        btnSubmitAnotherLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmitAnotherLink.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/submitAnotherButtonMouseOver.png"))); // NOI18N
        btnSubmitAnotherLink.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/submitAnotherButtonMouseOver.png"))); // NOI18N
        add(btnSubmitAnotherLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 280, 50));
        btnSubmitAnotherLink.setVisible(false);

        btnGoBackToHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/GoBackToHomeButton.png"))); // NOI18N
        btnGoBackToHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 166, 166)));
        btnGoBackToHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBackToHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/GoBackToHomeMouseOver.png"))); // NOI18N
        btnGoBackToHome.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PollsByYouButonMouseOver.png"))); // NOI18N
        add(btnGoBackToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 280, 50));
        btnGoBackToHome.setVisible(false);

        lblThanks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/TY4Submitting.png"))); // NOI18N
        add(lblThanks, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 240, 80));
        lblThanks.setVisible(false);

        lblUsername.setText("Username :");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        lblFullName.setText("Full name  :");
        add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        lblCredits.setText("Credits      : ");
        add(lblCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btnPollsByYou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PollsByYouButon.png"))); // NOI18N
        btnPollsByYou.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 166, 166)));
        btnPollsByYou.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPollsByYou.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PollsByYouButonMouseOver.png"))); // NOI18N
        btnPollsByYou.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PollsEngagementButtonMouseover.png"))); // NOI18N
        btnPollsByYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPollsByYouActionPerformed(evt);
            }
        });
        add(btnPollsByYou, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 280, 50));

        btnPollEngagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PollsEngagementButton.png"))); // NOI18N
        btnPollEngagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 166, 166)));
        btnPollEngagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPollEngagement.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PollsEngagementButtonMouseover.png"))); // NOI18N
        btnPollEngagement.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PollsEngagementButtonMouseover.png"))); // NOI18N
        add(btnPollEngagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 280, 50));

        lblInfo1.setText("Long press on the text field ");
        add(lblInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        lblInfo1.setVisible(false);

        lblInfo2.setText("and press paste");
        add(lblInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        lblInfo2.setVisible(false);

        lblBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/FakeOffHomeBackground.png"))); // NOI18N
        add(lblBackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        btnHomeButtonPressed();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnHomeButtonPressed() {
        showNewLinkElements(false);
        showHomeElements(true);
        showProfileElements(false);
        lblBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/resources/FakeOffHomeBackground.png")));
    }
    
    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        showNewLinkElements(false);
        showHomeElements(false);
        showProfileElements(true);
        
        lblBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/resources/FakeOffProfileBackground.png")));
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnNewLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewLinkActionPerformed
        showNewLinkElements(true);
        showHomeElements(false);
        showProfileElements(false);
        lblBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/resources/FakeOffNewLinkBackground.png")));


    }//GEN-LAST:event_btnNewLinkActionPerformed

    private void btnPollsByYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPollsByYouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPollsByYouActionPerformed

    private void btnSubmitLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitLinkActionPerformed
        String link = txtLink.getText().trim();

        if (link.compareTo("") == 0) {
            txtLink.setText("paste a link");

        } else {
            try {
                String username, query;

                Class.forName("java.sql.DriverManager");
                Connection con = DriverManager.getConnection("jdbc:mysql://"
                        + "localhost/FakeNewsApp", "User", "");

                Statement statment = con.createStatement();

                username = user.getUsername();
                /*insert into LINKDB (link, username) values
                  ('link', 'username');                       */
                query = "insert into LINKDB (link, username) values"
                        + "( '" + link + "', '" + username + "' );";

                statment.execute(query);
                Logger.addMessage("link has been added");

                thank();
            } catch (ClassNotFoundException | SQLException e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnSubmitLinkActionPerformed

    private void txtLinkFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLinkFocusGained
        if (txtLink.getText().compareTo("paste a link") == 0) {
            txtLink.setText("");
        }
    }//GEN-LAST:event_txtLinkFocusGained

    private void btnPasteFromClipboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasteFromClipboardActionPerformed
        try {
            Toolkit toolkit = Toolkit.getDefaultToolkit();
            Clipboard clipboard = toolkit.getSystemClipboard();
            String result = (String) clipboard.getData(DataFlavor.stringFlavor);

            txtLink.setText(result);

        } catch (UnsupportedFlavorException | IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnPasteFromClipboardActionPerformed

    private void btnFakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFakeActionPerformed
        nextNews();
    }//GEN-LAST:event_btnFakeActionPerformed

    private void btnNotFakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotFakeActionPerformed
        nextNews();
    }//GEN-LAST:event_btnNotFakeActionPerformed

    private void btnBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowserActionPerformed
        String url = news.link.get(iterator);
        try{
            openWebpage(new URL(url));
        } catch (MalformedURLException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBrowserActionPerformed

    public void showNewLinkElements(boolean status) {
        btnSubmitLink.setVisible(status);
        jScrollPane1.setVisible(status);
        txtLink.setVisible(status);
        txtLink.setText("");
        lblInfo1.setVisible(status);
        lblInfo2.setVisible(status);
        btnPasteFromClipboard.setVisible(status);
    }
    
    public void showHomeElements(boolean status){
        btnNotFake.setVisible(status);
        btnFake.setVisible(status);
        btnBrowser.setVisible(status);
        lblIcon.setVisible(status);
        lblHeadline.setVisible(status);
    }

    public void showProfileElements(boolean status) {
        lblUsername.setVisible(status);
        lblFullName.setVisible(status);
        btnPollEngagement.setVisible(status);
        lblCredits.setVisible(status);
        btnPollsByYou.setVisible(status);

    }

    private void thank() {
        showNewLinkElements(false);

        btnSubmitAnotherLink.setVisible(true);
        btnSubmitAnotherLink.addActionListener((ActionEvent evt) -> {
            lblThanks.setVisible(false);
            btnSubmitAnotherLink.setVisible(false);
            btnGoBackToHome.setVisible(false);

            showNewLinkElements(true); //displays the NewLink page
        });

        lblThanks.setVisible(true);

        btnGoBackToHome.setVisible(true);
        btnGoBackToHome.addActionListener((ActionEvent evt) -> {
            lblThanks.setVisible(false);
            btnSubmitAnotherLink.setVisible(false);
            btnGoBackToHome.setVisible(false);

            btnHomeButtonPressed(); //back to the home(starting) page
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowser;
    private javax.swing.JButton btnFake;
    private javax.swing.JButton btnGoBackToHome;
    public javax.swing.JButton btnHome;
    public javax.swing.JButton btnNewLink;
    private javax.swing.JButton btnNotFake;
    private javax.swing.JButton btnPasteFromClipboard;
    private javax.swing.JButton btnPollEngagement;
    private javax.swing.JButton btnPollsByYou;
    public javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSubmitAnotherLink;
    private javax.swing.JButton btnSubmitLink;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackgroundImage;
    private javax.swing.JLabel lblBlankWhite;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblHeadline;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblThanks;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextArea txtLink;
    // End of variables declaration//GEN-END:variables
}
