/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newspoll;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.logging.Level;
/**
 *
 * @author shayak
 */
public class MainFrame extends javax.swing.JFrame {

    public Logger log;
    private String username, password, fullName="", credits="";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FakeOff");
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(281, 500));
        getContentPane().setLayout(null);

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/loginButton.png"))); // NOI18N
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/loginButtonClicked.png"))); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(50, 340, 160, 50);
        btnLogin.setContentAreaFilled(false);

        txtPassword.setForeground(new java.awt.Color(158, 158, 158));
        txtPassword.setText("Password");
        txtPassword.setToolTipText("");
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(40, 230, 190, 27);

        txtUsername.setForeground(new java.awt.Color(154, 154, 154));
        txtUsername.setText("Username");
        txtUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(40, 180, 190, 27);

        btnSignUp.setBorder(null);
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnSignUp);
        btnSignUp.setBounds(90, 440, 100, 30);
        btnSignUp.setContentAreaFilled(false);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/loginBackground.png"))); // NOI18N
        lblBackground.setText("jLabel2");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, -20, 280, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        System.out.println("log: login page hidden");
        loginPageSetVisible(false);
        //TODO: add logger information
        
        checkLogin();
        
        
        if (true) {
            HomePage panelHomePage = new HomePage();
            this.add(panelHomePage);
            panelHomePage.setBounds(0, 0, 281, 500);
            
            panelHomePage.createUser(username, password, fullName, credits);
            panelHomePage.setVisible(true);
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        // TODO add your handling code here:
        txtUsername.setText("");
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        // TODO add your handling code here:
        String text = txtUsername.getText();
        if (text.compareTo("") == 0) {
            txtUsername.setText("Username");
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    public void loginPageSetVisible(boolean status) {
        btnLogin.setVisible(status);
        txtPassword.setVisible(status);
        txtUsername.setVisible(status);
        btnSignUp.setVisible(status);
        lblBackground.setVisible(status);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void checkLogin() {
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String fullName="user not found", credits="";
        
        //TODO: Remove after testing
        username = "testUser01";
        password = "password";
        
        try {
            //CODE FOR JDBC
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/FakeNewsApp",
                    "User", "");
            
            Statement statement = con.createStatement();
            ResultSet result = statement.executeQuery("SELECT * FROM USERDB where username='"
                + username + "';");
            
            while(result.next()){
                System.out.println(result.getString("password"));
                fullName = result.getString("name");
                credits = result.getString("credits");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
        
        this.username = username;
        this.password = password;
        this.credits = credits;
        this.fullName = fullName;
        
    }
}
